### ISSUE TITLE
Question - Perserve Dynamic Hyperlinks?

### ISSUE THREAD

**Issue by betocantu93** [forge512/ember-printable-pages#191]
Hello, this is such a great addon, thanks a lot! it actually cost me some trouble to make it work for our particular use case, because we have a very opinionated way of rendering dynamic forms, dealing with json schema spec, I think a nice enhancement would be to letting the client inject it's own section implementation, like making the whole addon as a template, like power-select does, mostly to be able to provide a custom way to iterate or having granular control over items or something like that, honestly I tried that road and hit a dead end, anyway, I handled it in a way the current API expects, and 👍 

## My real concern is how to deal with _hyperlinks_? 

When generating the PDF via <kbd>CMD</kbd> + <kbd>P</kbd> Chromium generated PDF ignores the hyperlinks, I know there's nothing this addon could do to make them work, but what would be a good approach (via extra libs, or something) to make it work?

**Comment by betocantu93** [comment]
There are a few ideas I've tried.

1. [html2pdf](https://www.npmjs.com/package/html2pdf.js/v/0.9.0) (many things can go wrong)
Do not use Chrome default printer, create an element, var doc = document.createElement('div') and somehow loop through the list of sections and items generated via printable pages and clone those nodes, doc.appendChild(section.clone(true))... and then html2pdf.from(doc).save();
the problem with this approach is that the items, and sections are all images, so you can copy + paste, but hyperlinks work.

2. Create an Iframe and print it
Iframe srcdoc
`<iframe srcdoc="<html><body></body></html>" />`

```ts
function createIframe(str){
   let iframe = document.createElement('iframe');
   iframe.onload = function() {
      var w = (this.contentWindow || this.contentDocument.defaultView);
            w.print();
    }
    iframe.srcdoc = str;
     return iframe
}
document.body.append(createIframe(SOME_HTML_STRING)) // the problem is that we need all the CSS to render it as expected?
```

**Comment by betocantu93** [comment]
In MacOS, Safari works like a charm, I'm impressed that Chronium doesn't handle this by default (dynamic generated links), there's a ton of SPA's out there....

**Comment by chbonser** [comment]
@betocantu93 Thanks for giving this addon a try and providing some feedback. 

**Making the section component more flexible**
Think that is a great idea. I'll chew on that and see what I can come up with.

**Hyperlinks**
I get how that is a critical need and agree that html2pdf has too many limitations. I've experimented with it as well. In addition to the inability to copy and paste the file size is significantly larger.

I tried saving a page to pdf using Chrome 83 and the resulting hyperlinks (a tags) were respected and worked in the PDF. In your use case are you rendering a tags with an href or something else (button with action that changes the route)?

**Comment by betocantu93** [comment]
@chbonser oh man, you are a wizard! hehe, by your suggestion I double checked and found that hyperlinks aren't working because we are using `locationType: 'hash'` (Corber app), I'm not sure TBH how to fix this... so the hrefs looks like this using `hash` `#/some-route`, if I change `locationType: auto` it works and save the PDF, it works!

**Comment by chbonser** [comment]
Interesting. I don't have a ready answer for you on that one. I'll think more on it though.

**Comment by betocantu93** [comment]
Yep, for the moment I think I'll leave pdf printing only for web and emails, and maybe implement Firebase Dynamic Links for deep linking 

https://www.youtube.com/watch?list=PLl-K7zZEsYLmOF_07IayrTntevxtbUxDL&time_continue=102&v=LvY1JMcrPF8&feature=emb_logo
